name: hello CI Pipeline

on: 
  push:
    branches:    
      - master  
    paths:
      - 'hello/**'
      - '**/hello.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd hello
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
        docker push $IMAGE_NAME
      env:
        IMAGE_NAME: 'hello'
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}


# options:
#     docker: true 
# pipelines:
#       default:
#         - step:
#             name: Build Image
#             script:
#                 - build_changes.sh
#         #         - cd hello
#         #         - export IMAGE_NAME=$DOCKER_USER/hello:latest
#         #         - docker build -t  $IMAGE_NAME .
#         #         - docker login -u $DOCKER_USER -p $DOCKER_PASS
#         #         - docker push $IMAGE_NAME
#         # - step:
#         #     name: Deploy to Kubernetes
#         #     image: atlassian/pipelines-kubectl
#         #     script:
#         #         - echo $KUBECONFIG | base64 -d > kubeconfig.yml
#         #         - kubectl --kubeconfig=kubeconfig.yml  apply -f app_k8s.yaml