name: hello CI Pipeline

on: 
  push:
    branches:    
      - master  
    paths:
      - 'hello/**'
      - '**/hello.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd hello
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
