name: hello CI Pipeline

on: 
  push:
    branches:    
      - master  
    paths:
      - 'hello/**'
      - '**/hello.yml'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init
      run: |
        echo $(date +%F-%H-%M-%S) > id.txt
        cd hello
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://teamint/vscode-python:latest
    - name: Testing
      run: |
        pip install requirements.txt 
        python -m pytest tests
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Artifact
      run: |
        TAG=$(cat id.txt)
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
      env:
        IMAGE_NAME: '${{ secrets.DOCKER_USER }}/hello'
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://atlassian/pipelines-kubectl
    - name: Deploy Artifact 
      run: |
        TAG=$(cat id.txt)
        
        echo $KUBECONFIG | base64 -d > kubeconfig.yml
        mkdir -p ~/.aws
        echo $AWS | base64 -d > ~/.aws/credentials

        sed -i 's/TAG/$TAG/g' k8s-deployment.yaml
        kubectl  --kubeconfig=kubeconfig.yml get pods --all-namespaces
        kubectl  --kubeconfig=kubeconfig.yml apply -f k8s-deployment.yaml
      env:
        IMAGE_NAME: '${{ secrets.DOCKER_USER }}/hello'
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        AWS: ${{ secrets.AWS }}