name: hello CI Pipeline

on: 
  push:
    branches:    
      - master  
    paths:
      - 'hello/**'
      - '**/hello.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Artifact
      run: |
        echo $(date +%F-%H-%M-%S) > id.txt
        EXPORT TAG=$(cat id.txt)
        cd hello
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$TAG
      env:
        IMAGE_NAME: '${{ secrets.DOCKER_USER }}/hello'
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://atlassian/pipelines-kubectl
    - name: Deploy Artifact 
      run: |
        echo $KUBECONFIG | base64 -d > kubeconfig.yml
        mkdir -p ~/.aws
        echo $AWS | base64 -d > ~/.aws/credentials
        kubectl  --kubeconfig=kubeconfig.yml get pods --all-namespaces
      env:
        IMAGE_NAME: '${{ secrets.DOCKER_USER }}/hello'
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        AWS: ${{ secrets.AWS }}