name: user CI Pipeline

on: 
  push:
    branches:    
      - master  
    paths:
      - 'user/**'
      - '**/user.yml'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Init
      run: |
        cd user
    - uses: docker://teamint/vscode-python:latest
    - name: Testing
      run: |
        cd user
        pip install -r requirements.txt
        python -m pytest tests
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Artifact & Deploy
      run: |
        cd user
        TAG=$(date +%F-%H-%M-%S)
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build . --file Dockerfile --tag teamint/user:$TAG
        docker push teamint/user:$TAG
        sed -i 's/TAG/$TAG/g' k8s-deployment.yaml
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    - uses: docker://atlassian/pipelines-kubectl
    - name: Deploy Artifact 
      run: |  
        cd user      
        echo $KUBECONFIG | base64 -d > kubeconfig.yml
        mkdir -p ~/.aws
        echo $AWS | base64 -d > ~/.aws/credentials
        
        kubectl  --kubeconfig=kubeconfig.yml apply -f k8s-deployment.yaml
        cat k8s-deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        AWS: ${{ secrets.AWS }}

        # kubectl  --kubeconfig=kubeconfig.yml get pods --all-namespaces
